# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_runtime_pb2 as agent__runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeServiceStub(object):
    """Durable control-plane boundary. Runtime metadata and chat history remain on
    the signed compatibility HTTP API until their contracts are equally stable.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/ratsnest.runtime.v1.AgentRuntimeService/StartRun',
                request_serializer=agent__runtime__pb2.StartRunRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.Run.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/ratsnest.runtime.v1.AgentRuntimeService/GetRun',
                request_serializer=agent__runtime__pb2.GetRunRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.Run.FromString,
                _registered_method=True)
        self.ControlRun = channel.unary_unary(
                '/ratsnest.runtime.v1.AgentRuntimeService/ControlRun',
                request_serializer=agent__runtime__pb2.ControlRunRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.Run.FromString,
                _registered_method=True)
        self.SubscribeRunEvents = channel.unary_stream(
                '/ratsnest.runtime.v1.AgentRuntimeService/SubscribeRunEvents',
                request_serializer=agent__runtime__pb2.SubscribeRunEventsRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.RunEvent.FromString,
                _registered_method=True)


class AgentRuntimeServiceServicer(object):
    """Durable control-plane boundary. Runtime metadata and chat history remain on
    the signed compatibility HTTP API until their contracts are equally stable.
    """

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRunEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=agent__runtime__pb2.StartRunRequest.FromString,
                    response_serializer=agent__runtime__pb2.Run.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=agent__runtime__pb2.GetRunRequest.FromString,
                    response_serializer=agent__runtime__pb2.Run.SerializeToString,
            ),
            'ControlRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlRun,
                    request_deserializer=agent__runtime__pb2.ControlRunRequest.FromString,
                    response_serializer=agent__runtime__pb2.Run.SerializeToString,
            ),
            'SubscribeRunEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRunEvents,
                    request_deserializer=agent__runtime__pb2.SubscribeRunEventsRequest.FromString,
                    response_serializer=agent__runtime__pb2.RunEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratsnest.runtime.v1.AgentRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratsnest.runtime.v1.AgentRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntimeService(object):
    """Durable control-plane boundary. Runtime metadata and chat history remain on
    the signed compatibility HTTP API until their contracts are equally stable.
    """

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratsnest.runtime.v1.AgentRuntimeService/StartRun',
            agent__runtime__pb2.StartRunRequest.SerializeToString,
            agent__runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratsnest.runtime.v1.AgentRuntimeService/GetRun',
            agent__runtime__pb2.GetRunRequest.SerializeToString,
            agent__runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratsnest.runtime.v1.AgentRuntimeService/ControlRun',
            agent__runtime__pb2.ControlRunRequest.SerializeToString,
            agent__runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ratsnest.runtime.v1.AgentRuntimeService/SubscribeRunEvents',
            agent__runtime__pb2.SubscribeRunEventsRequest.SerializeToString,
            agent__runtime__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
