CREATE TABLE IF NOT EXISTS design_runs (
    id VARCHAR(255) PRIMARY KEY
);

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS attempt INTEGER DEFAULT 0 NOT NULL;
