ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS dispatch_phase VARCHAR(20) DEFAULT 'execute' NOT NULL;

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS plan_contract_version VARCHAR(80);

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS plan_sha256 VARCHAR(64);

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS plan_created_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS plan_approved_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE design_runs
    ADD COLUMN IF NOT EXISTS plan_json TEXT;
