apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - telemetry.yaml
  - dashboard.yaml
patches:
  - path: patch-control-plane.yaml
  - path: patch-runtime.yaml
  - path: patch-web.yaml
